'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class useradmin
    
    '''<summary>
    '''frmUA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmUA As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''Img2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Img2 As Global.System.Web.UI.HtmlControls.HtmlImage
    
    '''<summary>
    '''datedisp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents datedisp As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''Toplinks1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Toplinks1 As Global.aprequest.Toplinks
    
    '''<summary>
    '''ulink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ulink As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tblUsrs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblUsrs As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblUsrsHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblUsrsHead As Global.System.Web.UI.WebControls.TableHeaderRow
    
    '''<summary>
    '''tuhName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuhName As Global.System.Web.UI.WebControls.TableHeaderCell
    
    '''<summary>
    '''tuhUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuhUsername As Global.System.Web.UI.WebControls.TableHeaderCell
    
    '''<summary>
    '''tuhManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuhManager As Global.System.Web.UI.WebControls.TableHeaderCell
    
    '''<summary>
    '''tuhEntity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuhEntity As Global.System.Web.UI.WebControls.TableHeaderCell
    
    '''<summary>
    '''tuhRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuhRegion As Global.System.Web.UI.WebControls.TableHeaderCell
    
    '''<summary>
    '''tuhSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuhSite As Global.System.Web.UI.WebControls.TableHeaderCell
    
    '''<summary>
    '''tuhLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuhLimit As Global.System.Web.UI.WebControls.TableHeaderCell
    
    '''<summary>
    '''tuhAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tuhAccount As Global.System.Web.UI.WebControls.TableHeaderCell
    
    '''<summary>
    '''lbAppr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAppr As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''ddEnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddEnt As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddReg As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddSite As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddFY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddFY As Global.System.Web.UI.WebControls.DropDownList
End Class
